services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Supseven\ThemeBase\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Supseven\ThemeBase\DataProcessing\LegalNoticeDataProcessor:
    public: true
    arguments:
      $pageRenderer: '@TYPO3\CMS\Core\Page\PageRenderer'

  Supseven\ThemeBase\Service\LegalNoticeService:
    public: true
    arguments:
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
